### ISSUE TITLE
Docker creates libs folder but Android.pk is looking for lib folder ... causing 'Could not resolve 'archive.ubuntu.com' 

### ISSUE THREAD

**Issue by samiHajjaj** [creativa77/roscpp_android#32]
Following the instructions of this tutorial http://wiki.ros.org/android_ndk/Tutorials/BuildingNativeROSPackages

a libs folder was created in the output folder ... where all the libraries are saved 

then, following the instructions of this tutorial http://wiki.ros.org/android_ndk/Tutorials/Building%20The%20Example%20Applications%20using%20the%20Binary%20Distribution

I get the LOCAL_SRC_FILES points to a missing file

the error message is .. 

Android NDK:  Could not locate  "bla bla: output/lib/ros_android_ndk, file does not exit  

Which indicates that the Android.pk was looking for lib folder even though the the ./do_docker created a libs folder 

any ideas ? .. thank you

**Comment by sami1977** [comment]
Here is the exact error codes 

     [exec] Android NDK: ERROR:/home/samihajjaj/ros-android-ndk/roscpp_android/output/roscpp_android_ndk/Android.mk:roscpp: LOCAL_SRC_FILES points to a missing file    
     [exec] Android NDK: Check that /home/samihajjaj/ros-android-ndk/roscpp_android/output/roscpp_android_ndk/lib/libroscpp.a exists  or that its path is correct   
     [exec] /opt/android-ndk-r10c/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

**Comment by sami1977** [comment]
I tried to edit the Android.mk file so it points to libs and not lib ==> didnt work 
I even changed the folder name to lib .... still didnt work .. in fact i realized that this wasnt just a folder name issue .... in fact the libroscpp.a  library does not exist at all !!! ... it wasnt generated following the /do_docker thing 

I gave up on ros-android-ndk .... or atleast using your approach ... too much automation !!

**Comment by sami1977** [comment]
issue resolved ... too bad i cant delete this .. can only close it 

i had forgotten to create the roscpp_out/target folder in /opt and put the lib and include folders there

**Comment by ernestmc** [comment]
Hi @sami1977. I'm glad you where able to make this work. Do you need any further help or can we proceed to close this issue?

**Comment by sami1977** [comment]
@ernestmc thank you for ur prompt response ... for now yes you can close this issue ... thank you for the support and all your efforts ... and i just realized tht i have two accounts on github .. hahaa

**Comment by sami1977** [comment]
@ernestmc thank you for ur prompt response ... for now yes you can close this issue ... thank you for the support and all your efforts 

PS; i just realized tht i have two accounts on github .. hahaa
